name: manage-azure-policy-7f1982d4
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/initiatives/_Preview_New_Zealand_ISM_Restricted_d1a462af-7e6d-4901-98ac-61570b4ed22a/**'
#      - .github/workflows/manage-azure-policy-7f1982d4.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_7f1982d4}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/initiatives/_Preview_New_Zealand_ISM_Restricted_d1a462af-7e6d-4901-98ac-61570b4ed22a/**
